### ISSUE TITLE
messagingServiceSid doesnt work

### ISSUE THREAD

**Issue by rierajf** [adarshbalu/twilio_flutter#38]
Hi,
Beautiful work ! I can send SMS, it's great !! Thanks. 
Although, use of messagingServiceSid doesn't seem to work. I received a SMS from the phone number (short) but not from the messagingService I configured in my Twilio console :-/

Normally, twilioNumber is not mandatory if we use messagingServiceSid :

curl 'https://api.twilio.com/2010-04-01/Accounts/[MyAccountSID]/Messages.json' -X POST \
--data-urlencode 'To=+33xxxxxxx' \
--data-urlencode 'MessagingServiceSid=[MyMessagingServiceId]' \
--data-urlencode 'Body=test' \
-u [MyAccountSID]:[AuthToken]

Thanks for your help
JF

**Comment by adarshbalu** [comment]
Thanks, @rierajf will look into the issue.

**Comment by adarshbalu** [comment]
Fixed in #41

**Comment by rierajf** [comment]
The parameter messagingServiceSid is not know anymore now. This parameter replaces the twilioNumber.

The problem is not solved at all.

[2024-06-17_21h25_46](https://github.com/adarshbalu/twilio_flutter/assets/131958062/7579c946-089d-4d2e-b10d-df195e78f398)


Thanks for your help

**Comment by adarshbalu** [comment]
Hi @rierajf, there has been an update to the service. Please refer to the README.

- Create a new TwilioMessagingService:
```dart
final TwilioMessagingService twilioMessagingService = TwilioMessagingService(
    accountSid: '', // replace with Account SID
    authToken: '', // replace with Auth Token
    messagingServiceSid: '' // replace with messaging service sid from twilio console
);
```
